# Generated by Django 5.0.1 on 2026-01-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCRDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_json', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
