# Generated by Django 5.0.1 on 2026-01-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocrdocument',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
